dept.id=1023
dept.name=IT
dept.loc=Pune

#emp1
emp1.eid=55
emp1.ename=Sahil
emp1.salary=98324
emp1.mobileno=7894561239
emp1.email=sahil@gmail.com

#emp2
emp2.eid=70
emp2.ename=Ameya
emp2.salary=47832
emp2.mobileno=9874561239
emp2.email=ameya@gmail.com


