Laptop.brand=HP
Laptop.price=54000
Laptop.ramCapacity=12gb
Laptop.hardDiskCapacity=1tb
Laptop.ssdCapacity=256gb
Laptop.color=Moonlight Blue


Manufacture.mid=562
Manufacture.company=Coforge
Manufacture.address=Pune